name: CI

on:
  pull_request:
    branches:
      - master
      - dev

jobs:
  test:
    runs-on: ubuntu-latest
    container: golang:1-alpine

    steps:
      - uses: actions/checkout@v2

      - name: Install Dependencies
        run: go mod download

      - name: Lint
        run: go test ./... -v
