name: Test Master

on:
  push:
    branches:
      - master

jobs:
  run-tests:
    name: Run tests on master
    runs-on: ubuntu-latest
    container: golang:1-alpine

    steps:
      - uses: actions/checkout@v2

      - name: Install Dependencies
        run: go mod download

      - name: Run Tests
        run: go test ./... -v
